Repository ScottRobinsonSky/MV-Week-4-Project, pull requests merged in 2022-10, with the labels that each got.

#1 CORS Server & Basic Input Workflow
  README.md
  cors-server/package-lock.json
  cors-server/package.json
  cors-server/server.js
  index.html
  script.js
  style.css
Labels: frontend, backend

#3 `displayError()` removes previously displayed errors
  script.js
Labels: frontend

#7 Add backend for retrieving data on featured games
  script.js
Labels: backend

#5 Merge search by id
  script.js
Labels: backend

#6 Updated list to include currency name
  data.js
  helpers/currency.json
  helpers/get-currency-list.js
  script.js
Labels: frontend, backend

#9 Add base frontend for displaying a searched game's data
  SVG/apple-black-logo-svgrepo-com.svg
  SVG/tux-svgrepo-com.svg
  SVG/windows-windows-svgrepo-com.svg
  SashasNotes.md
  index.html
  script.js
  style.css
Labels: frontend

#10 Display error when CORS server not running
  script.js
Labels: frontend

#11 Add a back button
  SVG/back-svgrepo-com-white.svg
  index.html
  script.js
  style.css
Labels: frontend

#12 Display N/A when no metacritic info available
  script.js
Labels: backend
